apiVersion: apps/v1
kind: Deployment
metadata:
  name: shodapp-backend-deployment
  namespace: shodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shodapp-backend
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2025-01-02T20:00:00Z'
      labels:
        name: shodapp-backend
    spec:
      containers:
        - name: shodapp-backend
          image: seansal/shodapp-k8s-backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5055
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: shodapp-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: shodapp-config
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: shodapp-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: shodapp-config
                  key: DB_NAME
            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: shodapp-config
                  key: JWT_SECRET_KEY
            - name: SHODAN_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: shodapp-config
                  key: SHODAN_API_KEY
