apiVersion: v1
kind: Service
metadata:
  name: shodapp-backend-svc
  namespace: shodapp
spec:
  selector:
    name: shodapp-backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5055
      targetPort: 5055