apiVersion: v1
kind: Service
metadata:
  name: shodapp-frontend-svc
  namespace: shodapp
spec:
  selector:
    app: shodapp-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP