apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shodapp
resources:
  - backend/backend-deployment.yml
  - backend/backend-svc.yml
  - frontend/frontend-deployment.yml
  - frontend/frontend-svc.yml