name: Frontend CI

on:
  pull_request:
    types:
      - closed
    paths:
      - 'k8s/frontend/**'

jobs:
  docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shodapp-k8s-frontend:${{ github.run_id }}
            ${{ secrets.DOCKERHUB_USERNAME }}/shodapp-k8s-frontend:latest

      - name: Update kubernetes manifests
        run: |
          git pull origin main
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          sed -i "s|kubectl.kubernetes.io/restartedAt: '.*'|kubectl.kubernetes.io/restartedAt: '$timestamp'|" k8s/frontend/frontend-deployment.yml
          git add k8s/frontend/frontend-deployment.yml
          git commit -m "Update frontend deployment timestamp for new image" || echo "No changes to commit"
          git push origin main
